apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-task-storage
  namespace: cnd-co-located-handson
spec:
  resources:
    requests:
      storage: 16Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
