apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-task-exercise-2-2
  namespace: cnd-co-located-handson
spec:
  params:
  - name: image-name
    description: "実行するコンテナイメージ"
    default: ubuntu
  workspaces:
    - name: shared
  steps:
    # - args:
    #     - sleep
    #     - '6000'
    #   image: docker
    #   name: pause
    - image: $(params.image-name)
      name: sample-step
#      resources:
#        requests:
#          memory: 500m
#          cpu: 500m
      script: |

        # WorkspaceのPVCの内容を確認
        cat /workspace/shared/sample.txt
